Milestone 2: Refactor to use JavaScript classes
grauJavier/awesome-books pull request #2
Opened 2023-05-31 22:48 UTC by grauJavier

# 🌟 New Features
- **Code Refactoring:** The `script.js` file has been refactored using classes to improve code organization and maintainability.
- **Enhanced CSS Styling:** Bootstrap has been implemented to enhance the visual appearance of the webpage, providing a more polished and professional look.

2023-05-31 23:43 UTC, t-yanick requested changes
# STATUS: CHANGES REQUIRED

Hi @grauJavier and @Dachrono , 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Collaborative work :+1:  
:heavy_check_mark: App works effectively after refactor

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- [x] When I click on the MIT license link, I am redirected to an error 404 page. Kindly fix this issue. It is not professional to keep broken links in our README
![image](https://github.com/grauJavier/awesome-books/assets/62849872/1d738f07-e18e-4e97-a870-a22b8f590c75)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 23:43 UTC, t-yanick commented on JS/script.js
> +  removeData(titleRemove) {
- [OPTIONAL ] 
You can use unique id property for each book since it would make it easier to remove books with duplicate values. See sample code below:
```javascript
  removeBook(bookID) {
    this.books = this.books.filter(({ id }) => bookID !== id); 
    return this.books; 
  }
```

2023-05-31 23:43 UTC, t-yanick commented on JS/script.js
> +    this.bookList.push(obj);
- [OPTIONAL ] 
Favor the use array methods that don't mutate the array, e.g. [concat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat), [filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter), [slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) instead of [push](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push), [pop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/pop), [splice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) and so on: see code example below
```javascript
  addBook(title, author) {
    id = generateID(); 
    this.books = this.books.concat({ title, author, author });
    return this.books; 
  }
```

2023-06-01 03:14 UTC, emmiiorji approved these changes
Hi @grauJavier, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights✔️

- Requested change has been implemented

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 03:18 UTC, merged